SCREEN_WIDTH = 3440
SCREEN_HEIGHT = 1440
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 5
ASTEROID_SPAWN_RATE = 0.6  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 180  # degrees per second
PLAYER_SPEED = 200  # pixels per second
PLAYER_SHOOT_SPEED = 500  # pixels per second
SHOT_RADIUS = 5
PLAYER_SHOOT_TIMER = 0.3